version: "3.7"

services:
  mariadb:
    container_name: metric_mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'dbmetric_passwd'
      MYSQL_DATABASE: 'dbmetric'
      MYSQL_USER: 'dbmetric_user'
      MYSQL_PASSWORD: 'dbmetric_passwd'
volumes:
  mariadb-data: